development:
  adapter: postgresql
  encoding: unicode
  database: starterapp_dev
  pool: 5
  username: martinho
  password: 
  

test:
  adapter: postgresql
  encoding: unicode
  database: starterapp_test
  pool: 5
  username: martinho
  password:
